// Generated by scripts/build-library.mjs from content/library/*.md.
// Do not edit by hand: edit the markdown and run `npm run library`.

import type { Resource } from "./resources";

/** The newest entry's date, so the site's last-updated date follows the library. */
export const libraryUpdated = "2026-09-14";

export const resources: readonly Resource[] = [
  {
    id: "spec-based-ai-development",
    title: "From Vibe Coding to Production: The 5-Step Spec-Based Framework",
    by: "Mahesh Yadav",
    url: "https://www.youtube.com/watch?v=6tDwGtMmqmc",
    theme: "Operating Model",
    media: "Video",
    time: "52 min watch",
    added: "2026-09-04",
    verdict: "Breaks down SDLC for non-technical PMs",
    note: "",
    tags: ["AI","spec-driven development","operating model"],
  },
  {
    id: "vercel-cpo-v0",
    title: "v0 Tutorial from the CPO: AI Prototype Like a Pro",
    by: "Aakash Gupta",
    url: "https://www.news.aakashg.com/p/tom-occhino-podcast",
    theme: "AI",
    media: "Video",
    time: "75 min watch",
    added: "2026-09-14",
    verdict: "The era of personalised software",
    note: "Insight into Vercel's operating model from its CPO, such as Notion, Slack and Linear cohesion and L3 to L1 roadmaps. Workflow flexibility: take the codebase and put it into your own process, with work underway at Vercel to make the flow even smoother. You can't capture all the content required in a demo or prototype, but don't double up with a PRD; they should be complementary.",
    tags: ["prototyping","vibe-coding","AI"],
  },
  {
    id: "boris-cherny-we-cut-80-of-claude-codes-prompt",
    title: "Boris Cherny: We Cut 80% of Claude Code’s Prompt",
    by: "Y Combinator",
    url: "https://www.youtube.com/watch?v=qyPCVqFUyDo",
    theme: "AI",
    media: "Video",
    time: "35 min watch",
    added: "2026-09-01",
    verdict: "Simplifies just how different building AI product is",
    note: "Lifts the hood. At the pace things are moving, you'll need to throw out rather than just iterate.",
    tags: ["improving-AI-products","anthropic","AI"],
  },
  {
    id: "marty-cagan-product-role",
    title: "A Fresh Definition of The Product Role",
    by: "Marty Cagan",
    url: "https://www.svpg.com/a-fresh-definition-of-the-product-role/",
    theme: "Career",
    media: "Article",
    time: "10 min read",
    added: "2026-09-12",
    verdict: "Reminder that the craft of product management still plays an important role, and what to continue to work on",
    note: "Living in the tech bubble can make us feel everyone is a builder, but just because they can doesn't mean they will: people have other jobs. Institutionalised vs improvised software. Make sure you read and listen to the links embedded in the article.",
    tags: ["product-management","AI-evolution"],
  },
  {
    id: "stop-using-claude-chat",
    title: "Stop Using Claude Chat. Get Into the Terminal.",
    by: "Veronika Wax",
    url: "https://veronikawax.substack.com/p/stop-using-claude-chat-get-into-the?r=4y7zy",
    theme: "Templates & Tools",
    media: "Article",
    time: "8 min read",
    added: "2026-09-14",
    verdict: "In a chat you get an answer. In a repo you get an asset.",
    note: "The inefficiency of continuing to work in Chat and Cowork environments: you lose your edge and get lower quality outputs. Memory, skills, and repeated or scheduled tasks, with step by step instructions and a simple breakdown.",
    tags: ["GTM","PMM","AI-powered","AI","templates & tools"],
  },
];
