// Generated by scripts/build-library.mjs from content/library/*.md.
// Do not edit by hand: edit the markdown and run `npm run library`.

import type { Resource } from "./resources";

export const resources: readonly Resource[] = [];
